### ISSUE TITLE
DeviantArt Error on Notification Post

### ISSUE THREAD

**Issue by SomewhatDamaged** [mvdicarlo/postybirb#289] opened 2024-09-22 02:01 UTC
Getting the following when trying to post a Notification (and no post appears):

```
DeviantArt: Failed to run script on page: Draft is not defined

script:

var blocksFromHTML = Draft.convertFromHTML(`<div>A new chapter of my story, The Heart Grows <a href="https://www.royalroad.com/fiction/51893/the-heart-grows,">https://www.royalroad.com/fiction/51893/the-heart-grows</a>, is now out!</div><br /><br /><p><a href="http://www.postybirb.com">Posted using PostyBirb</a></p>`);
var x = Draft.ContentState.createFromBlockArray(
blocksFromHTML.contentBlocks,
blocksFromHTML.entityMap,
)
return JSON.stringify(Draft.convertToRaw(x))
```

V: 3.1.47

- [x] Checked that I'm logged in
- [x] Posted to multiple other sites at the same time (Bluesky, SoFurry, etc)

**Comment by leaftail1880** [comment] 2024-09-22 07:58
This is a known error that has been reported even here although this is repo of the unpublished PostyBirb V4. Please check out https://github.com/mvdicarlo/postybirb-plus/issues/360 and close this issue

**Comment by SomewhatDamaged** [comment] 2024-09-22 08:04
Then perhaps the website needs altering?

I downloaded the version I have from https://www.postybirb.com/download.html and that links to this repo for V3.

**Comment by leaftail1880** [comment] 2024-09-28 07:54
Can you please close this issue as for DA its been fixed and for NG its a known issue (duplicate of https://github.com/mvdicarlo/postybirb-plus/issues/311)

**Comment by SomewhatDamaged** [comment] 2024-09-28 07:55
Oh, dang, sorry. I thought I had.

**Closed** 2024-09-28 07:55 UTC
